jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory:
      ~/app

    branches:
      only:
        - master

    steps:
      - checkout

      - run:
          name: "build app"
          command: gradle build
      - run:
          name: "copy jar"
          command: cp build/libs/*.jar cts-server-latest.jar

      - setup_remote_docker

      - run:
          name: "create and push docker image"
          environment:
              DOCKER_HUB_ACCT: eevirendra
              DOCKER_HUB_REPOSITORY: cicd-server
              PASSWORD: Security@s1
          command: |
              docker build -t $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM .
              docker tag  $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:latest
              docker login -u $DOCKER_HUB_ACCT -p $PASSWORD
              docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM
              docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:latest
    deployment:
      staging:
        branch: master
        heroku:
          appname: cicd-server